name: CI Workflow with Matrix Builds

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print greeting
        run: echo "Hello, CI with GitHub Actions! Running on Python ${{ matrix.python-version }}"

#      - name: Install dependencies (optional)
#        run: pip install -r requirements.txt || true

      - name: Run tests
        run: python -m unittest discover

